using System.ComponentModel.DataAnnotations.Schema;
using NoRslinx.Domain.Entities;
using NoRslinx.Domain.Enums;

namespace NoRslinx.Domain.Entities;

/// <summary>
/// Database Model of Micrologix PLCs
/// </summary>
/// <remarks> List of Parameters for Micrologix PLCs
///     <para>
///     <list type="bullet">
///     <item>
///         <term>Id</term>
///         <description>: Primary Key</description>
///         <description>, Autogenerated</description>
///     </item>
///     <item>
///         <term>Name</term>
///         <description>: Nullable</description>
///         <description>, Not Required</description>
///     </item>
///     <item>
///         <term>IpAddress</term>
///         <description>: Nullable</description>
///         <description>, Not Required</description>
///     </item>
///     <item>
///         <term>Location</term>
///     </item>
///     <item>
///         <term>Description</term>
///     </item>
///     <item>
///         <term>Program</term>
///         <description>: Program loaded on the PLC</description>
///     </item>
///     <item>
///         <term>TimeoutSeconds = </term>
///         <description>> 5 </description>
///     </item><item>
///         <term>PlcType = </term>
///         <description>> "PlcType.Slc500" </description>
///     </item><item>
///         <term>Protocol = </term>
///         <description>> "Protocol.ab_eip" </description>
///     </item>
///     </list>
///     </para>
///
/// </remarks>
/// <param name="PlcId">Primary Key: Auto-Increments on Creation</param>
/// <param name="Name">Name of the PLC (NULLABLE)</param>
/// <param name="IpAddress">Plc's IpV4 Address (NULLABLE)</param>
/// <param name="Location"></param>"
/// <param name="Description"></param>"
/// <param name="Program"></param>"
/// <param name="PlcType">[ Default: "PlcType.Slc500" ] : Type of PLC</param>
/// <param name="Protocol">[ Default: "ab_eip" ] : Protocol used to communicate with PLC</param>
/// <param name="Timeout">[ Defualt: 5 ] : Timeout in Seconds </param>
/// <param name="DebugLevel">[ Default: "DebugLevel.None" ] : Debug Level</param>
///
public class MicrologixPlc : BaseAuditableEntity
{
    public string? Name { get; set; }
    public string? IpAddress { get; set; }

    public string? Location { get; set; }

    public string? Description { get; set; }

    public string? Program { get; set; }

    public PlcType PlcType { get; set; } = PlcType.Slc500;
    public Protocol Protocol { get; set; } = Protocol.ab_eip;


    [Column(TypeName = "time(0)")]
    public TimeSpan Timeout { get; set; } = TimeSpan.FromSeconds(5);

    public DebugLevel DebugLevel { get; set; } = DebugLevel.None;

    public IList<PlcTag> PlcTags { get; set; } = new List<PlcTag>();
}


